# Generated by Django 4.0.5 on 2022-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(verbose_name='Order ID')),
                ('costUSD', models.FloatField(verbose_name='Cost, $')),
                ('costRUB', models.FloatField(verbose_name='Cost, RUB')),
                ('deliveryDate', models.DateField(verbose_name='Delivery Date')),
            ],
            options={
                'managed': True
            },
        ),
    ]
